#!/usr/bin/env python3
"""
check_loadorder.py - verify client/server plugin parity for SkyMP.

Compares:
  1. a client plugins.txt (active entries start with '*') against the
     server's loadOrder from server-settings.json  -> order and membership
  2. optionally, files in a client Data folder against the server's
     data/manifest.json (crc32 + size per plugin)  -> byte parity

Usage:
  check_loadorder.py --plugins plugins.txt --settings server-settings.json
  check_loadorder.py --plugins plugins.txt --settings server-settings.json \
      --manifest data/manifest.json --client-data "/path/to/Skyrim/Data"
  check_loadorder.py --manifest data/manifest.json --client-data /path/Data   (parity only)

Notes:
  * plugins.txt lives in %LOCALAPPDATA%\\Skyrim Special Edition\\plugins.txt on
    Windows (or the MO2 profile folder). Lines starting with '#' are comments,
    '*' marks an active plugin, lines without '*' are inactive.
  * The five vanilla masters are implicitly active and may be absent from
    plugins.txt; they are inserted automatically.
  * manifest.json is generated by the server at startup. Do not edit it.
Exit code 1 on any mismatch.
"""
import argparse
import json
import os
import sys
import zlib

VANILLA = ["Skyrim.esm", "Update.esm", "Dawnguard.esm", "HearthFires.esm", "Dragonborn.esm"]


def parse_plugins_txt(path):
    active = []
    with open(path, "r", encoding="utf-8-sig", errors="replace") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("*"):
                active.append(line[1:].strip())
    # vanilla masters are implicit; prepend any that are missing
    for m in reversed(VANILLA):
        if m not in active:
            active.insert(0, m)
    # keep vanilla in canonical order at the front
    rest = [p for p in active if p not in VANILLA]
    return VANILLA + rest


def crc32_of(path):
    crc = 0
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            crc = zlib.crc32(chunk, crc)
    return crc & 0xFFFFFFFF


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--plugins", help="client plugins.txt")
    ap.add_argument("--settings", help="server-settings.json")
    ap.add_argument("--manifest", help="server data/manifest.json")
    ap.add_argument("--client-data", help="client Data folder for crc32/size parity")
    args = ap.parse_args()

    problems = []

    server_lo = None
    if args.settings:
        try:
            with open(args.settings, "r", encoding="utf-8") as f:
                server_lo = json.load(f).get("loadOrder")
        except json.JSONDecodeError as e:
            problems.append(f"{args.settings} is not strict JSON: {e}")
        except OSError as e:
            problems.append(f"{args.settings}: {e}")
        if server_lo is not None and not isinstance(server_lo, list):
            problems.append("loadOrder is not a list")
            server_lo = None

    manifest = None
    if args.manifest:
        try:
            with open(args.manifest, "r", encoding="utf-8") as f:
                manifest = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            problems.append(f"{args.manifest}: {e}")
        if manifest and server_lo is None and isinstance(manifest.get("loadOrder"), list):
            server_lo = manifest["loadOrder"]
            print("Using loadOrder from manifest.json")

    if args.plugins and server_lo is not None:
        client_lo = parse_plugins_txt(args.plugins)
        print(f"client active plugins: {len(client_lo)}   server loadOrder: {len(server_lo)}")
        only_client = [p for p in client_lo if p not in server_lo]
        only_server = [p for p in server_lo if p not in client_lo]
        for p in only_client:
            problems.append(f"active on client but not in server loadOrder: {p}")
        for p in only_server:
            problems.append(f"in server loadOrder but not active on client: {p}")
        common_client = [p for p in client_lo if p in server_lo]
        common_server = [p for p in server_lo if p in client_lo]
        if common_client != common_server:
            problems.append("ORDER MISMATCH for shared plugins:")
            width = max(len(p) for p in common_client + common_server) if common_client else 10
            problems.append(f"    {'client'.ljust(width)}  | server")
            for i in range(max(len(common_client), len(common_server))):
                c = common_client[i] if i < len(common_client) else ""
                s = common_server[i] if i < len(common_server) else ""
                mark = "" if c == s else "   <-- differs"
                problems.append(f"    {c.ljust(width)}  | {s}{mark}")
        for p in server_lo:
            if p.lower().endswith(".esl"):
                problems.append(f"server loadOrder contains .esl (unsupported): {p}")
        # case-insensitive duplicates hint
        lowered = {}
        for p in client_lo + server_lo:
            lowered.setdefault(p.lower(), set()).add(p)
        for k, v in lowered.items():
            if len(v) > 1:
                problems.append(f"same plugin with different casing (Linux is case-sensitive): {sorted(v)}")
    elif args.plugins and server_lo is None:
        problems.append("--plugins given but no server loadOrder could be loaded (--settings or --manifest)")

    if manifest and args.client_data:
        mods = manifest.get("mods", [])
        print(f"manifest lists {len(mods)} mod file(s); checking against {args.client_data}")
        # case-insensitive lookup for Windows-style client folders
        listing = {n.lower(): n for n in os.listdir(args.client_data)}
        for m in mods:
            fname = m.get("filename")
            if not fname:
                continue
            real = listing.get(fname.lower())
            if not real:
                problems.append(f"manifest file missing on client: {fname}")
                continue
            p = os.path.join(args.client_data, real)
            size = os.path.getsize(p)
            crc = crc32_of(p)
            if "size" in m and size != m["size"]:
                problems.append(f"size differs: {fname} client={size} server={m['size']}")
            if "crc32" in m and crc != int(m["crc32"]):
                problems.append(f"crc32 differs: {fname} client={crc:08x} server={int(m['crc32']):08x}")
            if real != fname:
                print(f"  note: case differs on client for {fname} (client has {real})")
    elif args.manifest and not args.client_data:
        print("manifest loaded; pass --client-data to verify crc32/size")

    print()
    if problems:
        print("PROBLEMS:")
        for p in problems:
            print(f"  - {p}")
        return 1
    print("Client and server plugin sets match.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
